name: Build and Store Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish application
      run: dotnet publish .\SimpleRegionApp.API\ -c Release -r linux-x64 -o out

    - name: Upload artifact to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: published-artifacts
        path: out/